version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: promotions-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=root:password@tcp(db:3306)/promotions_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    container_name: promotions-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: promotions_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  redis:
    image: redis:latest
    container_name: promotions-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  db_data: