version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: promotions-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=root:password@tcp(db:3306)/promotions_db
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0
    container_name: promotions-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: promotions_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

volumes:
  db_data:
