name: Playground
on: 
  push:
    branches:
      - master

jobs:
  job-1:
    name: Job 1
    runs-on: ubuntu-latest
    steps: 
      - run: echo script 
      - uses: actions/checkout@v4
        with:
          ref: master
      - run: ls -lachs
      - uses: ./.github/actions/testAction
        with: 
          color: yellow